### ISSUE TITLE
MacGesture doesn't seem to work in Big Sur 11.0 Beta (20A5343j)

### ISSUE THREAD

**Issue by ppixu** [MacGesture/MacGesture#100]
Tried to allow in accessibility settings, didn't help.

**Comment by wangzhaoming** [comment]
Open settings, and remove MacGesture from the list. Then restart the app and allow it again.
It works for me on the Big Sur official version.

**Comment by akaseon** [comment]
> Open settings, and remove MacGesture from the list. Then restart the app and allow it again.
> It works for me on the Big Sur official version.

it works well.

**Comment by wuyf789** [comment]
不行,重新设置,还是一样闪退,不能用呀
