### ISSUE TITLE
macOS Big Sur support

### ISSUE THREAD

**Issue by wuyf789** [MacGesture/MacGesture#101]
重新设置,一样还是闪退 ,不能用呀

**Comment by username0x0a** [comment]
Hi, could you try my forked version https://github.com/username0x0a/MacGesture in its latest release? It has some work over this regular version and last time I tried, it worked fine with Big Sur. Feel free to file possible issues! 👍

**Comment by jiegec** [comment]
@username0x0a Are you interested in maintaining this project?

**Comment by username0x0a** [comment]
@jiegec Sure, I could handle that! 👍

**Comment by jiegec** [comment]
@xcodebuild Could you add @username0x0a as a member of MacGesture organization?

**Comment by xcodebuild** [comment]
@jiegec Invitation has been sent. Welcome @username0x0a  ~

**Comment by jiegec** [comment]
@username0x0a You are welcomed to merge your changes to the repo now. I can provide the necessary Chinese translations and give you the release signing key.

**Comment by cooliean** [comment]
我用了username0x0a这个大哥的版本页不行
```
 CFRunLoopSourceRef runLoopSource = CFMachPortCreateRunLoopSource(kCFAllocatorDefault, mouseEventTap, 0);
        CFRunLoopAddSource(CFRunLoopGetCurrent(), runLoopSource, kCFRunLoopCommonModes);
        CFRelease(mouseEventTap);
        CFRelease(runLoopSource);
```
这个的问题，但是不会修改，：）

**Comment by mtjo** [comment]
用MacStroke 吧,一直在更新优化,基于MacGesture 加了很多功能,java 程序的右键问题也解决了,更支持任意自定义手势 https://github.com/mtjo/MacStroke/releases/tag/2.0.0

**Comment by jiegec** [comment]
@mtjo 如果你有兴趣扩展 MacGesture 的话，我们乐意请你来加入维护。

**Comment by xcodebuild** [comment]
@mtjo 如果有兴趣解决问题请发 PR，不要在多个 issue 下刷广告甚至恶意编辑 Wiki

![image](https://user-images.githubusercontent.com/5436704/104676289-09367300-5722-11eb-9f94-85db848a1c69.png)

偷偷改链接保留文字的行为让我感觉到极大的恶意

仅这个 issue 的问题请临时使用  https://github.com/username0x0a/MacGesture 这个 fork 版，或者等待新的 maintainer @username0x0a  在主分支上修复。

---

@mtjo If you are interested in solving the problem, please send PR. Do not post ads under multiple issues  or even maliciously edit the Wiki.

The act of secretly changing the link and retaining the text makes me feel extremely malicious

For this issue only, please temporarily use https://github.com/username0x0a/MacGesture this fork version, or wait for the new maintainer @username0x0a to fix it on the main branch.

**Comment by mtjo** [comment]
> @mtjo 如果有兴趣解决问题请发 PR，不要在多个 issue 下重复刷广告甚至恶意编辑 Wiki
> 
> ![image](https://user-images.githubusercontent.com/5436704/104677206-fb81ed00-5723-11eb-81ba-1019e59fcbf6.png)
> ![image](https://user-images.githubusercontent.com/5436704/104677237-09377280-5724-11eb-99bf-318b1b5ce1fa.png)
> ![image](https://user-images.githubusercontent.com/5436704/104677246-0d639000-5724-11eb-989d-848beb2ae638.png)
> 
> ![image](https://user-images.githubusercontent.com/5436704/104676289-09367300-5722-11eb-9f94-85db848a1c69.png)
> 
> 偷偷改链接保留文字的行为让我感觉到极大的恶意
> 
> 仅这个 issue 的问题请临时使用 https://github.com/username0x0a/MacGesture 这个 fork 版，或者等待新的 maintainer @username0x0a 在主分支上修复。
> 
> @mtjo If you are interested in solving the problem, please send PR. Do not post ads under multiple issues or even maliciously edit the Wiki.
> 
> The act of secretly changing the link and retaining the text makes me feel extremely malicious
> 
> For this issue only, please temporarily use https://github.com/username0x0a/MacGesture this fork version, or wait for the new maintainer @username0x0a to fix it on the main branch.

抱歉,链接问题是我失误, 在这里表示歉意,我刚刚仔细看了一下 diff, 我补充了下载地址(没写错),和项目地址(这个是写错的,可能是因为我macstroke软件添加了历史粘贴板的原因,会有1000个历史记录)就是这一个链接写错了
另外,这个 wiki 也是我几年前整理的,之前 的 wiki 甚至没放到 github 上,在一个什么平台我也忘记了,
还有"希望能参考Easystroke 完全自定义手势"几年前这个是我提出来的,当年春节把算法写出来MacGesture原作者(星落，说想念)还给我发了个大红包,当时就考虑合到MacGesture 但是当时改动太多了,合并太多冲突,和作者(星落，说想念)商量另起了一个名称发布,因为功能是参考 linx 下的easystroke ,所以起名 macstroke,我从没想过把它当成一个新的软件,这是最近快过年闲下来了,有空重新优化macstroke,快5年了,macstroke加了很多功能,要合并回MacGesture难度很大,我添加了历史粘贴板,右键菜单,还有针对 java 应用开发了右键插件,最近又加了远程控制功能(能通过微信小程序控制电脑,还可以把 ipad,或手机当成触摸板用),这么多东西我不知道合到MacGesture会有多少冲突.
MacGesture存在的问题我基本都修复了,太多冲突没有合并到MacGesture,但是代码开源,我解答 issuse只是为了大家多一个选择,说实话,macstroke的功能是我针对工作中用到的功能开发的,开源也是为了帮到有相同需求的人,
开源不易,请大家支持MacGesture ,macstroke是个性化定制软件,不推荐使用,但MacGesture存在的问题我的项目代码可以参考修复,
致敬 MacGesture 开发维护者

**Comment by mtjo** [comment]
> @mtjo 如果有兴趣解决问题请发 PR，不要在多个 issue 下重复刷广告甚至恶意编辑 Wiki
> 
> ![image](https://user-images.githubusercontent.com/5436704/104677206-fb81ed00-5723-11eb-81ba-1019e59fcbf6.png)
> ![image](https://user-images.githubusercontent.com/5436704/104677237-09377280-5724-11eb-99bf-318b1b5ce1fa.png)
> ![image](https://user-images.githubusercontent.com/5436704/104677246-0d639000-5724-11eb-989d-848beb2ae638.png)
> 
> ![image](https://user-images.githubusercontent.com/5436704/104676289-09367300-5722-11eb-9f94-85db848a1c69.png)
> 
> 偷偷改链接保留文字的行为让我感觉到极大的恶意
> 
> 仅这个 issue 的问题请临时使用 https://github.com/username0x0a/MacGesture 这个 fork 版，或者等待新的 maintainer @username0x0a 在主分支上修复。
> 
> @mtjo If you are interested in solving the problem, please send PR. Do not post ads under multiple issues or even maliciously edit the Wiki.
> 
> The act of secretly changing the link and retaining the text makes me feel extremely malicious
> 
> For this issue only, please temporarily use https://github.com/username0x0a/MacGesture this fork version, or wait for the new maintainer @username0x0a to fix it on the main branch.

另外 按你的说法这个难道不一个广告吗?
>Hi, could you try my forked version https://github.com/username0x0a/MacGesture in its latest release? It has some work over this regular version and last time I tried, it worked fine with Big Sur. Feel free to file possible issues! 👍

**Comment by xcodebuild** [comment]
## 关于 Wiki

> 抱歉,链接问题是我失误, 在这里表示歉意,我刚刚仔细看了一下 diff, 我补充了下载地址(没写错),和项目地址(这个是写错的,可能是因为我macstroke软件添加了历史粘贴板的原因,会有1000个历史记录)就是这一个链接写错了
另外,这个 wiki 也是我几年前整理的,之前 的 wiki 甚至没放到 github 上,在一个什么平台我也忘记了

你修改的是 MacGesture 的 Wiki，不是你的 Wiki。

## 关于广告

> 另外 按你的说法这个难道不一个广告吗?

> > Hi, could you try my forked version https://github.com/username0x0a/MacGesture in its latest release? It has some work over this regular version and last time I tried, it worked fine with Big Sur. Feel free to file possible issues! 👍

不是，这是一个可以被合并回主分支的 fork 版本。

而是你连续在三个 issue 下发了三个广告，并且直接篡改了 MacGesture 的 Wiki 时我才指出的问题。如果仅仅是发了一条我觉得是不会引起抵触的。

**Comment by mtjo** [comment]
> @mtjo 如果你有兴趣扩展 MacGesture 的话，我们乐意请你来加入维护。

我每次修复功能都会在作者创建的群里公告,你们只要复制代码过去就能修复了,@xcodebuild 都能成为 member,我8年的 objective-c软件开发生涯不敢加入,我代码开源不设置任何限制,你们拿去就能用,我还是做一个偷偷改链接的程序猿就好,以前星落有问题会直接找,而不是用键盘侠的方式,另外之前有fork MacGesture 已经unfork,unstart ,另外感谢@xcodebuild对我中肯的评价
![images](https://github.com/mtjo/MacStroke/raw/images/%E6%88%AA%E5%B1%8F2021-01-15%2014.29.10.png)

**Comment by mtjo** [comment]
> Wiki

键盘侠你好,如果你是一个 developer,那你应该明白什么是 wiki
如果不明白百度给你粘贴一下:
>>Wiki是一种在网络上开放且可供多人协同创作的超文本系统，由沃德·坎宁安于1995年首先开发，这种超文本系统支持面向社群的协作式写作，同时也包括一组支持这种写作。沃德·坎宁安将wiki定义为“一种允许一群用户用简单的描述来创建和连接一组网页的社会计算系统”。 [1]  Wiki站点可以有多人（甚至任何访问者）维护，每个人都可以发表自己的意见，或者对共同的主题进行扩展与探讨。

另广告已删除,不会在你的 issues出现(是删库跑跑那种),不知道你能不理解是什么意思
星落以前有问题会直接qq 找我,你们倒好,只能呵呵了

**Comment by richardo2016** [comment]
@mtjo 我先把你发的话截图放在这里，看过一段时间你会不会后悔自己草率地打了这些话 [doge]

![image](https://user-images.githubusercontent.com/6339390/104694730-91c70a80-5746-11eb-9cdd-dcfa8c68c1a8.png)

**Comment by xcodebuild** [comment]
@mtjo 
1.  我就是你说的星落，原作者，我之所以直接在这里回仅仅是因为我现在不怎么用 qq，而且我是在 Github 通知上看到 @jiegec che 回滚了才知道 wiki 被人改了。
2. 我未曾就你个人为人做出任何评价，无论是中肯的或者不中肯的
3. 这个你是因为 wiki 是开放多人协作的，默认**信任**所有参与的贡献者，所以不需要 review。因此直接把 MacGesture 的 wiki 链接不吭声的换成自己的软件正符合『恶意编辑』，因为破坏了这种**信任**。
4. 这个讨论就到此为止吧，无需相互攻击

**Comment by username0x0a** [comment]
Guys, this has turned insane…

@mtjo: posting a link to your fork would be acceptable in case it's okay with maintainers here, but what's really my concern is the fact you've completely dropped the license information and references to original work and authors which is a clear license violation, supporting a possibility to report and drop your repository completely. So, first things first, please fix this issue to even legally have a faintest word in this discussion.

**Comment by mtjo** [comment]
> @mtjo
> 
> 1. 我就是你说的星落，原作者，我之所以直接在这里回仅仅是因为我现在不怎么用 qq，而且我是在 Github 通知上看到 @jiegec che 回滚了才知道 wiki 被人改了。
> 2. 我未曾就你个人为人做出任何评价，无论是中肯的或者不中肯的
> 3. 这个你是因为 wiki 是开放多人协作的，默认**信任**所有参与的贡献者，所以不需要 review。因此直接把 MacGesture 的 wiki 链接不吭声的换成自己的软件正符合『恶意编辑』，因为破坏了这种**信任**。
> 4. 这个讨论就到此为止吧，无需相互攻击

请你认真看wiki 的 diff,我的修改是没没有意义的吗?
引用上面的内容
>抱歉,链接问题是我失误, 在这里表示歉意,我刚刚仔细看了一下 diff, 我补充了下载地址(没写错),和项目地址(这个是写错的,可能是因为我macstroke软件添加了历史粘贴板的原因,会有1000个历史记录)就是这一个链接写错了
另外,这个 wiki 也是我几年前整理的,之前 的 wiki 甚至没放到 github 上,在一个什么平台我也忘记了,
还有"希望能参考Easystroke 完全自定义手势"几年前这个是我提出来的,当年春节把算法写出来MacGesture原作者(星落，说想念)还给我发了个大红包,当时就考虑合到MacGesture 但是当时改动太多了,合并太多冲突,和作者(星落，说想念)商量另起了一个名称发布,因为功能是参考 linx 下的easystroke ,所以起名 macstroke,我从没想过把它当成一个新的软件,这是最近快过年闲下来了,有空重新优化macstroke,快5年了,macstroke加了很多功能,要合并回MacGesture难度很大,我添加了历史粘贴板,右键菜单,还有针对 java 应用开发了右键插件,最近又加了远程控制功能(能通过微信小程序控制电脑,还可以把 ipad,或手机当成触摸板用),这么多东西我不知道合到MacGesture会有多少冲突.
MacGesture存在的问题我基本都修复了,太多冲突没有合并到MacGesture,但是代码开源,我解答 issuse只是为了大家多一个选择,说实话,macstroke的功能是我针对工作中用到的功能开发的,开源也是为了帮到有相同需求的人,
开源不易,请大家支持MacGesture ,macstroke是个性化定制软件,不推荐使用,但MacGesture存在的问题我的项目代码可以参考修复,
致敬 MacGesture 开发维护者

有话直说,我不明白我怎么就成了 "偷偷改链接保留文字的行为让我感觉到极大的恶意"

**Comment by wuyf789** [comment]
解决了，哈哈哈哈，厉害，感谢分享价值

**Comment by username0x0a** [comment]
I'm using my forked version with Big Sur and it's working just fine 👍 also – I have a visual update in progress:

<img width="651" alt="Big Sur toolbar" src="https://user-images.githubusercontent.com/5228484/105630240-50221800-5e48-11eb-807d-d47470bdc45c.png">

I believe it will integrate very well with Big Sur and M1 as well. 🙌

One thing @xcodebuild @jiegec – seems like I can't perform push or any settings update of the repository. Can you take a look and grant me write & managing permissions?

**Comment by jiegec** [comment]
@xcodebuild Could you give @username0x0a a favor? I only have the signing key, but not the permission of the organization.

**Comment by xcodebuild** [comment]
@jiegec  Done, both @username0x0a and @jiegec had the owner role of this group now.

**Comment by username0x0a** [comment]
I'd like to push a major 3.0 update during the weekend 👍 I need to find out whether Apple Notarisation will work fine or do we have a special App Store Connect account for this? Also I'll need those `Sparkle` resources so the update correctly appears to current users.

**Comment by jiegec** [comment]
> I'd like to push a major 3.0 update during the weekend 👍 I need to find out whether Apple Notarisation will work fine or do we have a special App Store Connect account for this? Also I'll need those `Sparkle` and `Homebrew` resources so the update correctly appears to current users.

I sent the Sparkle private key to you by email.

**Comment by username0x0a** [comment]
@jiegec @xcodebuild Guys, could you take a look at Chinese translation at https://github.com/MacGesture/MacGesture/tree/develop/MacGesture/Resources/zh-Hans.lproj and walk through the localised strings? In best case please take the English ones from https://github.com/MacGesture/MacGesture/tree/develop/MacGesture/Resources/en.lproj as those contain the exact needed set of strings required for translation. Thanks, we're close! 👍

**Comment by username0x0a** [comment]
Update is now live! 🎉 Sparkle update procedure went successfully both in Catalina and Big Sur from 2.2.5, both OSes are working  just fine 👌 can't really test Apple M1 support, but I guess than one will work well, too. 😄 Enjoy, guys!
