### ISSUE TITLE
zip broken with system unzip

### ISSUE THREAD

**Issue by xcodebuild** [MacGesture/MacGesture#102]
![1548871339](https://user-images.githubusercontent.com/5436704/106407613-76af0700-6477-11eb-88d4-d8952b5aff9f.jpg)

![image](https://user-images.githubusercontent.com/5436704/106407552-49faef80-6477-11eb-8f3f-268f2bd41db1.png)

works with The Unarchiver but not with default Archive Utility

Seems related to https://forum.xojo.com/t/catalina-unzip-file-permissions-problems/52435/15

**Comment by username0x0a** [comment]
It works fine with either the system Archive Utility and The Unarchiver when I try. 🤔

Moreover, when inspecting with _BetterZip_, the particular file rights seem to be okay for all the app bundle, folders and the actual executable:

<img width="983" alt="Screenshot 2021-02-08 at 18 01 21" src="https://user-images.githubusercontent.com/5228484/107254545-b22d7080-6a37-11eb-9f5f-1b516ccd0a2e.png">

all of them having the `x` right present. This ZIP is also used by _Sparkle_ and _Homebrew_, both seem to unpack the app properly.

Any other idea how shall we debug this?

**Comment by xcodebuild** [comment]
I download zip from release and unzip it again, it works fine this time...
