### ISSUE TITLE
close all tabs to the left. 

### ISSUE THREAD

**Issue by dongqizhen15** [MacGesture/MacGesture#104]
> 🇬🇧 Please write the feedback in English if possible so everyone who might read it will be able to respond easily! 👍

**close all tabs to the left. **
As the CrxMouse gesture shows. Contains general gestures and mouse gestures. 

![image](https://user-images.githubusercontent.com/41569076/115098348-38978e80-9f62-11eb-92c8-4ed599c1a946.png)
![image](https://user-images.githubusercontent.com/41569076/115098356-40573300-9f62-11eb-9149-37d1f3df1fc1.png)
![image](https://user-images.githubusercontent.com/41569076/115098363-49480480-9f62-11eb-9c12-dbdcefdd1687.png)

**Comment by bytemain** [comment]
CrxMouse is a Chrome Extension so it can controll chrome behavior, but MacGesture can only use your keyboard.

You can assign some keyboard shorrtcut to `close all tabs to the left`, and let MacGesture trigger the keyboard shortcut.

https://superuser.com/questions/298576/chrome-keyboard-shortcut-to-close-other-tabs
