### ISSUE TITLE
JetBrain等软件使用后没有办法使用右键菜单

### ISSUE THREAD

**Issue by cooliean** [MacGesture/MacGesture#107]
IDEA WebStrom 等软件使用手势可以实现相应的功能，但是软件本身的右键菜单不能使用了。

MacGesture 版本 3.0.0

MacOS 11.3

IDEA  2021.1.1

**Comment by HaHeho** [comment]
Can confirm that it prevents rick-clicking for me as well.

MacGesture 3.1.0

MacOS 11.6.2

PyCharm 2021.3.1

**Comment by HaHeho** [comment]
I tried to find a workaround apart from the one you mentioned by adjusting the IDE keymap setting. I suppose the the most straightforward (but easy to forget about) workaround is to just use [control]+[left click]. 😄

**Comment by bytemain** [comment]
<img width="588" alt="image" src="https://user-images.githubusercontent.com/13938334/164140697-1f85e3a5-ea75-4a57-aa3b-4866d2ada5ec.png">

**Comment by bytemain** [comment]
在 IntelliJ IDEA 2022.2.3 和 Ventura 这个问题不会再出现了，先关闭了。

有问题可以再开启。
