### ISSUE TITLE
希望添加：总是作用于鼠标下方的窗口选项

### ISSUE THREAD

**Issue by wangasd** [MacGesture/MacGesture#109]
总是作用于光标下方的窗口 
既：命令或快捷键总是发送给光标（鼠标）下方的窗口或应用， 即使焦点没有在此窗口或应用上
希望配制成可选项。

目前是总是作用在焦点窗口上。

例如： mac开浏览器和ide开两个窗口，此时无论光标所在这个窗口是否有焦点，都可以用鼠标滚轮或触摸板直接滚动此窗口，而不是先让窗口获取焦点。

如果，焦点在ide上，我去浏览器滑动页面。需要先点击一下浏览器获取焦点才能滑动页面，这不会让人很崩溃么？

**Comment by bytemain** [comment]
duplicated with: https://github.com/MacGesture/MacGesture/issues/115
