### ISSUE TITLE
Open at login not working

### ISSUE THREAD

**Issue by Micha125** [MacGesture/MacGesture#111]
Hey there,

just installed MacGesture and recognized that the program is not opening automatically at startup. I already enabled this in the Preferences - General section. But whenever I restart my computer, I have to open the app manually and the setting is not enabled anymore.

How can I fix this?

I am using MacOS Monterey 12.0.1 on a Mac Mini M1 and version 3.0.0 of MacGesture.

Best Regards, Michael

**Comment by jiegec** [comment]
Hi Michael,

It is working in macOS Big Sur here, and I will test on macOS Monterey later.

**Comment by Micha125** [comment]
Hey jiegec,

thanks very much! Could you already test it?

**Comment by username0x0a** [comment]
I'll try on my M1 Mac mini 🤔 Apple may have changed the way services do register to run on startup (more precisely, deprecate the previously used method in favour of a newer service type). Good point is I'll have to try booting both OSes as it might get more complicated between those updates as well as there are OS-level differences between Intel and Apple Silicon platforms as well.

**Comment by username0x0a** [comment]
It works on Monterey on an Intel Mac 🤔 will test it on Apple Silicon as well to see if it's something weird different down in system-level APIs. Could you also try unticking the option in MacGesture Preferences, removing it from System Preferences → Users & Groups  → YOUR ACCOUNT → Login Items if present, closing Preferences, and add again via MacGesture Preferences?

**Comment by Micha125** [comment]
Thank You! Unfortunately, removing and adding the option did not work, MacGesture is still not opening automatically on startup.

**Comment by username0x0a** [comment]
Just tested Big Sur on M1 and it works 🤨 so I'll give more feedback after installing Monterey on a different partition. Temporarily, you could untick the option in MacGesture Preferences, delete the item if present in System Preferences pane, and add it only using the System Preferences – it should be a system-level feature to fire up any application on startup, not depending on any application. So another possibility is, that system option is broken, too. 😄

**Comment by username0x0a** [comment]
Okay, just tested and it works on my Mac mini M1, both in Big Sur and Monterey, the same applies to 16" MacBook Pro with Intel. 🤔 By any chance, do you see any error messages in Console app when enabling live logging and switching the “Start at Login” option, or alternatively, using the system-provided dialog in System Preferences?

**Comment by Micha125** [comment]
Well, I just drag and drop the application in the application folder and now it's working! Thanks for all your help :)

**Comment by username0x0a** [comment]
Ah, I see 🤔 well there's a concept of Gatekeeper Path Randomization where the application is believed to have a random path when running, unless it's placed in `/Applications` – good to know it also affects things like this, definitely thanks for the feedback 👍 I think we could check this on checking that specific option.

**Comment by username0x0a** [comment]
Added a simple app path checker on the feature checkbox in the 3.1 release. ✅
