### ISSUE TITLE
This executes the action at the moment that the completed gesture is recognized, but it should instead execute when the mouse is released, and should execute the most complicated gesture matched.

### ISSUE THREAD

**Issue by theedgeofoblivious** [MacGesture/MacGesture#112]
I used to use xGestures, but it's not compatible with M1 Macs(possibly yet or possibly ever). Someone recommended MacGesture, and said it was better in terms of flexibility, but I noticed an issue. I have an extensive list of gestures. Some are really simple, like just dragging up to create a new tab in my browser, dragging left to go back, or dragging right to go forward in my browser.

I noticed that MacGesture fires the moment I execute this gesture, so if I have a more complicated gesture I am trying to execute, it doesn't. It immediately executes the gesture as it's matched.

If instead you only executed the gesture when the mouse button was released and counted the number of recorded directions(Up, Down, Left, Right) and then only executed the gesture matching the highest number of directions seen, it would allow a lot more flexibility than just executing the gesture at the moment it notices that the directions have matched a known gesture.

**Comment by username0x0a** [comment]
The gestures shouldn't really fire immediately by default AFAIK 🤔 there's a checkbox on the trailing side of every gesture row which toggles this specifically. Having that checkbox unticked should wait for that specific gesture to be fully matched. Maybe you have some other (shorter) conflicting gesture fired immediately (with ticked checkbox) which overrides it? 🤔

**Comment by theedgeofoblivious** [comment]
Wonderful! The purpose of that checkbox was a little unclear with that column header being only a few pixels wide, but if I uncheck the boxes, everything works exactly as expected. Thanks very much.

**Comment by username0x0a** [comment]
I agree, the column presentation is a bit confusing now, I'll try to address it in the next release. 👍
