### ISSUE TITLE
Monterey support?

### ISSUE THREAD

**Issue by Rhywun** [MacGesture/MacGesture#116]
Nothing works in Monterey.

Steps to reproduce the behaviour:
1. Installed with homebrew, version 3.1.0
2. Granted permissions in Accessibility settings as prompted
3. Looked at the Preferences that opened, didn't change anything, closed Preferences
4. Tried suggested built-in gesture to close a tab in Safari
5. Got the usual context-menu when right-clicking, unable to see or create a gesture
6. Quit and restarted Safari, same behavior

**Expected behaviour**
A working gesture

**Desktop**
macOS Monterey, version 12.1
iMac (Retina 5K, 27-inch, 2017)
Magic Mouse
Safari version 15.2

Thank you!

**Comment by alezzblezz** [comment]
Same here, MacBook Air M1, same versions

**Comment by rico** [comment]
It works for me after an update / restart. Don't know if the update or restart helped. Mac Mini M1 now on macOS 12.3.

**Comment by username0x0a** [comment]
After allowing permissions, does just restarting MacGesture help? 🤔

**Comment by Rhywun** [comment]
> After allowing permissions, does just restarting MacGesture help? 🤔

I don't recall if I had quit and restarted MacGesture during my first tests. It's possible I didn't.

Just relaunched and for whatever reason, it's now working. I look forward to playing with the options, thanks!

macOS Monterey, version 12.3.1
Safari version 15.4

**Comment by username0x0a** [comment]
I'll check the onboarding flow, anyway, just in case 👍 it's still a bit far from ideal. Thanks for your feedback!
