### ISSUE TITLE
MacGesture会导致MacOS授权类对话框无法点击

### ISSUE THREAD

**Issue by Gav1nMa** [MacGesture/MacGesture#124]
MacGesture版本：3.1
MacOS版本：12.4
反复出现情境：
1、首次运行Parallels Desktop中的虚拟机时，需要授权虚拟机访问MacOS中的某些文件夹、授权访问摄像头等等，这些对话框弹出来均无法被允许或拒绝，只有关闭MacGesture后方可点击；
2、在其他设备上登陆了iCloud账号后，已登陆该iCloud账号的Mac电脑会弹出一条提示，内容大致如“账号在其他某某设备上登陆使用”的系统对话框，只要后台运行着MacGesture就无法关闭此对话框，关掉就可以。
类似以上的情境还有很多很多，只要是涉及授权类、系统提示类的对话框，MacGesture在后台运行中就无法被点击，必须要关掉MacGesture才能正常使用。
我一直认为是自己的MacOS系统出了问题，反复重装、恢复系统，均未解决问题，后来在国外某论坛才有人提到是MacGesture带来的影响。
请开发者或有能力之士解决此问题，也希望正在被此问题困扰的用户按我现在的解决方法去做！

**Comment by bytemain** [comment]
看起来是在 macos 12.4 上会出现这个问题？https://www.v2ex.com/t/854017
我现在使用的 macos 13 已经不会有这个问题了。

**Comment by seagle0128** [comment]
遇到这个问题好久了，一直没能解决

**Comment by godfather1103** [comment]
好像12.5正常了，目前来看没问题

**Comment by seagle0128** [comment]
确认升级到12.5没问题了

**Comment by bytemain** [comment]
看起来是 MacOS 升级版本导致的问题，升级到 12.5 以上不会有这个问题了，暂时不知道如何修复。
如果再遇到可以再打开。
