### ISSUE TITLE
希望没有添加手势时不要占用这个序列

### ISSUE THREAD

**Issue by asterho** [MacGesture/MacGesture#125]
我希望在其他程序中指定“right click + u/d"为快捷键，但目前即使没有添加手势，这个序列会也会被被占用

**Comment by username0x0a** [comment]
Have you tried the rule with a ⚡️ check checked as well? 🤔

**Comment by bytemain** [comment]
这个问题应该是由于多个鼠标软件对鼠标事件的响应问题。

MacGesture 在捕获到鼠标事件后，再释放发出去的事件可能其他软件就不能捕获到了（因为如果其他软件能捕获到，这个软件就又会捕获一次，大家就无限死循环了）。

你可以提供下使用的其他软件，我这里尝试下是不是我说的这个问题。

**Comment by asterho** [comment]
> 这个问题应该是由于多个鼠标软件对鼠标事件的响应问题。
> 
> MacGesture 在捕获到鼠标事件后，再释放发出去的事件可能其他软件就不能捕获到了（因为如果其他软件能捕获到，这个软件就也能捕获到，就会再捕获一次，大家就无限死循环了）。
> 
> 你可以提供下使用的其他软件，我这里尝试下是不是我说的这个问题。

我使用的软件是steermouse，是一个用来自定义鼠标按键、滚轮的软件。我用它来实现右键+滚轮=左右滚动的功能，但这样会和MacGesture的手势冲突。按你说这样，看来是没有特别好的解决方法了。或者能不能使用别的键来触发手势功能呢？

**Comment by asterho** [comment]
> Have you tried the rule with a ⚡️ check checked as well? 🤔

Sorry for replying so late, I have tried ⚡️, but it doesn't work for my issue.

**Comment by bytemain** [comment]
研究了一下，和其他手势软件一起用没有特别好的解决方法。

[使用别的键来触发手势功能] 在这里跟踪 -> https://github.com/MacGesture/MacGesture/issues/56
