### ISSUE TITLE
Triggering Mission Control

### ISSUE THREAD

**Issue by thisiskun** [MacGesture/MacGesture#126]
**Describe the bug**
gesture can not trigger mission control

**Steps To Reproduce**
set a gesture UR map to control + up shortcut 

**Expected behaviour**
can see the gesture note but not trigger mission contorl

**Screenshots**
![image](https://user-images.githubusercontent.com/1177353/183608352-289a3c89-7101-416d-91f5-356bde2e4f33.png)

 - Version 3.1.0

**Comment by username0x0a** [comment]
I have no idea this ever even worked 🤔 but I found a nice workaround using the AppleScript integration – by adding (AppleScript tab) and binding (Gestures tab → Add AppleScript rule) this script:

```applescript
tell application "System Events"
	key code 160 -- Show Mission Control
end tell
```

you can trigger showing and dismissing Mission Control no probs. 👌 I'll probably add this script to the loadable examples list as well.

**Comment by Jopp-gh** [comment]
> I have no idea this ever even worked 🤔 but I found a nice workaround using the AppleScript integration – by adding (**AppleScript** tab) and binding (**Gestures** tab → `+` **Add AppleScript rule**) this script:

Avoid "system events", just call "mission control" directly. 
 
```applescript
 tell application "Mission Control" to launch
```
