### ISSUE TITLE
首先感觉作者,可否添加如下功能:

### ISSUE THREAD

**Issue by yuyangzxw** [MacGesture/MacGesture#28]
1:可否选择隐藏菜单栏图标
2:可否添加右键+滚轮的组合,这个貌似一些游览器出现的比较多:按住鼠标右键,滚动滚轮可以直接到达页首或者页尾
再次感谢作者的好软件

**Comment by jiegec** [comment]
1. 可以考虑。
2. 感觉很难用 Apple Mouse 同时按住右键又滑动。。你是怎么做到的。。

**Comment by yuyangzxw** [comment]
谢谢作者回复,其实我就是普通的无线鼠标,所以...
不过麻烦的话就算了...

**Comment by jiegec** [comment]
这个应该是可以做到的，可以考虑。

**Comment by yuyangzxw** [comment]
谢谢了,能添加的话最好了,影响程序性能什么的话,慢慢来好了,再次感谢了

**Comment by jiegec** [comment]
第一个功能已经在HEAD实现了。第二个我有个想法，要不要把滚轮向上和手势向上合并？而且这里还要考虑两种滚轮方向。。

**Comment by yuyangzxw** [comment]
谢谢解答,其实现在的功能我已经用着很舒服了,第二个功能无所谓的,毕竟用的不多,页面很长的网页还是蛮少的,短的页面滚轮滚下基本问题不大的
再次感谢作者

**Comment by jiegec** [comment]
Long time without activity, thus closing.
