### ISSUE TITLE
2.0.10 Todos

### ISSUE THREAD

**Issue by jiegec** [MacGesture/MacGesture#29]
- [x] Apple Script support #27
- [x] Add showing or hiding the menu icon as a option.
- [ ] More possible gestures? Integrate with on-mouse gestures. #28 
- [x] i18n or l10n.
- [x] In-App locale selector.

**Comment by jiegec** [comment]
Spent the whole afternoon on Apple Script support.

**Comment by jiegec** [comment]
@CodeFalling Any points on improving the performance issue?

**Comment by CodeFalling** [comment]
@jiegec Not yet.I am downloading `XCode` again and again..

**Comment by jiegec** [comment]
@CodeFalling I have made a dirty hack.

**Comment by CodeFalling** [comment]
However it works more slowly now.Maybe it's nothing about performance.Just drawing is slower (triggered) than moving of mouse.
