### ISSUE TITLE
2.1.0会导致Mission Control触发角失效

### ISSUE THREAD

**Issue by syxc** [MacGesture/MacGesture#31]
MacGesture 的 v2.1.0 版本，貌似会导致 Mission Control 的触发角失效。

**测试过程：**
重启机器后，没有使用鼠标手势前触发角正常，触发鼠标手势后 Mission Control 触发角失效，下载 v2.0.9 替换 v2.1.0 版本 Mission Control 无异常现象。

**猜测：**
v2.1.0 版本导致的 Mission Control 触发角异常。

@CodeFalling @jiegec @zhangciwu 有空看看？

**Comment by CodeFalling** [comment]
试了下我这边似乎无法重现这个问题

**Comment by jiegec** [comment]
@syxc 无法重现。我这里设置了左下到Misson Control然后并没发现问题。

**Comment by jiegec** [comment]
Can't reproduce. Any stacktrace?

**Comment by jiegec** [comment]
Wait I somehow reproduced it.

**Comment by jiegec** [comment]
时有时无。

**Comment by CodeFalling** [comment]
fixed in 2.1.1, thx to @jiegec
