### ISSUE TITLE
2.10 导致webstorm 右键点击后无法使用

### ISSUE THREAD

**Issue by zhangciwu** [MacGesture/MacGesture#32]
在webstorm点右键
然后菜单无法选择
然后在webstorm里面，点击左键会变成右键
导致菜单一直出来，无法使用

之后在finder中拖动文件也会无法使用，无法把文件放下。

（放着我来修复！

**Comment by jiegec** [comment]
然而怎么看起来都和我们这一段时间的改动没关系哈。。。

**Comment by zhangciwu** [comment]
目前看来可能和某个鼠标事件没有正确返回或正确注销有关

**Comment by jiegec** [comment]
恩我看了API发现我们写的有问题。

**Comment by zhangciwu** [comment]
这么快~ 我稍等试试

**Comment by jiegec** [comment]
Using Android Studio, but no abnormal behaviour observed.

**Comment by jiegec** [comment]
Can't reproduce. Any stacktrace available?

**Comment by zhangciwu** [comment]
在webstorm -》左侧文件列表点右键
然后菜单无法选择
然后在webstorm里面，点击左键会变成右键
导致菜单一直出来，无法使用

你按照这个顺序试试看看

**Comment by jiegec** [comment]
@zhangciwu 还是试不出来。

**Comment by zhangciwu** [comment]
装个pycharm或者webstorm试试看看？
androidstuidio我没用过

**Comment by jiegec** [comment]
IntelliJ IDEA passed.

**Comment by PythonFX** [comment]
老版本的jetbrains的软件都不会与本软件冲突
我最近新装了CLion 是2016.1.1版本的 直接不能右键
然后顺手升级了pycharm到2016.1.2也不能用
后来才发现是与MacGesture冲突
暂时的解决办法是把冲突的jetbrains软件黑名单了

当然 如果你需要在这些软件里用鼠标手势的话 这个方案不行

我觉得不能算是MacGesture的问题 更应该算是jetbrains的问题
毕竟其他的软件 是没有右键冲突问题的

**Comment by jiegec** [comment]
@PythonFX 这个我这总是重现不了，很奇怪。

**Comment by jiegec** [comment]
还有问题吗？

**Comment by zhangciwu** [comment]
新版已经好了
