### ISSUE TITLE
希望能够增加类似按住鼠标右键再按左键触发相关动作的功能

### ISSUE THREAD

**Issue by PythonFX** [MacGesture/MacGesture#33]
之前chrome中某些鼠标手势软件里
会提供先按右键再按左键 或反过来的 所谓鼠标手势
而我个人很喜欢这种手势
并把这俩手势都对应到关闭标签页（也有人喜欢映射到切换左侧和右侧的标签页）

总之我觉得这个是鼠标上最快捷轻松的手势
希望MacGesture能够增加该手势
这样我就能更方便的关闭标签页/窗口（或者其他功能）了

非常感谢这款很棒的系统增强软件~

**Comment by jiegec** [comment]
最近又有人通过右键重提这个问题，我来说一下这里会遇到的一些技术问题。
1. 截获更多鼠标按键，并且记录按键顺序，这个不难。
2. 鼠标按键和ShortcutRecorder如何结合呢？如果在按键过程中滑动，那么应该按照什么来决定触发哪一个规则？如果滑动后继续按键，又该如何？重新计算滑动吗？
3. 考虑如何将这个新的功能和以前的功能做到兼容，即backward-compatibility.

**Comment by jiegec** [comment]
现在可以了。
