### ISSUE TITLE
MBP 2015 版本 鼠标不会跟着移动

### ISSUE THREAD

**Issue by xcc3641** [MacGesture/MacGesture#34]
功能是可以实现，但是右键移动后鼠标就指针不会跟随。

**Comment by jiegec** [comment]
这里是MBA 2011并没有问题。这个应该和机型没有太大关系（万一呢）。请问你用的是哪一个版本的MacGesture呢？

**Comment by xcc3641** [comment]
我刚刚才下载的呢 2.1.1

**Comment by jiegec** [comment]
有没有更详细的信息？我们这里并不能重现，也帮不到你什么。。

**Comment by xcc3641** [comment]
![](http://ww4.sinaimg.cn/large/006tNbRwgw1f5uv4vtcraj30u40l0q4s.jpg)


起点 —-> 终点，鼠标并没有移动

**Comment by jiegec** [comment]
No idea.

**Comment by jiegec** [comment]
Any update?

**Comment by jiegec** [comment]
问题还在吗？

**Comment by jiegec** [comment]
你好，现在新版本出来了，问题仍然存在吗？

**Comment by jiegec** [comment]
Long time without activity, thus closing.
