### ISSUE TITLE
Minimal distance?

### ISSUE THREAD

**Issue by 2called-chaos** [MacGesture/MacGesture#35]
Just discovered this nice piece of software :)

I've got one question. Is it possible to define a minimal distance the mouse have to travel before triggering the gesture?

I sometimes try to open the context menu but move a little bit and trigger the navigation shortcuts I've setup. Something like "at least 100px" or it doesn't trigger.

Cheers!

**Comment by jiegec** [comment]
Hmmm, yes but it should be hardcoded by now. Let me check.

**Comment by jiegec** [comment]
Here is the code:
```
NSPoint newLocation = event.locationInWindow;
    double deltaX = newLocation.x - lastLocation.x;
    double deltaY = newLocation.y - lastLocation.y;
    double absX = fabs(deltaX);
    double absY = fabs(deltaY);
    if (absX + absY < 20) {

        return; // ignore short distance
    }
```
It detects the new move within 20 points using Manhattan distance. Isn't it small enough?

**Comment by 2called-chaos** [comment]
It indeed triggers when I moved 20 pixels and this is a little bit *too small* / too sensitive for me :) My screen resolution is 1920x1200 (16:10 monitor).

It would be awesome if that could be a setting in the GUI. I'm not sure if it should be just the initial threshold for the first move or also apply to successive direction changes if you know what I mean.

I don't know if I can do it but I'll try to compile it with 80-100px which would be fine for me.

**Comment by jiegec** [comment]
Yes we can implement it, but 'one man's meat is another man's poison', it's hard to cater for everyone. Now there are options like:

1. Initial threshold pixels and successive threshold pixels;
2. threshold = f(width, height)

I am thinking to include a lua-based customization system now ;).

**Comment by jiegec** [comment]
Any comments?

**Comment by 2called-chaos** [comment]
I tried to compile it but I'm a total noob in these things and [couldn't get it to compile](). I mean any way of changing just that number would be awesome but I guess I can live with the current setting as well, just have to be more careful or make my gestures more complex (not just left/right for navigation).

Maybe it's just me but if others have issues with this as well some sort of setting might be good :-)

**Comment by jiegec** [comment]
haha you may need to execute `pod install` and then open the xcworkspace instead of xccodeproj.
I can add that customization but I don't want to expose it through the UI. Waiting for more people interested in it.

**Comment by ww7** [comment]
gestureSize in com.codefalling.MacGesture.plist not affect to this issue

Just missing half of "Right Clicks"

**Comment by jiegec** [comment]
that setting only applies to the gesture drawn... not the detection logic

**Comment by ww7** [comment]
This issue exist only with unchecked "Disable Mouse Path" in Preferences.

If "Disable Mouse Path" checkbox is ✓ — context menu appear without issues, but if Rule with Trigger✓ — context menu appear after gesture.

And we have another issue with Trigger X)

**Comment by jiegec** [comment]
This is already fixed in master.

**Comment by jiegec** [comment]
Fixed in commit 5456d5e

**Comment by 2called-chaos** [comment]
Thank you very much, can't wait for the release :)

From my very little ObjC knowledge: This way you could use `defaults write ...` right?

**Comment by jiegec** [comment]
```
defaults write com.codefalling.MacGesture directionDetectionThreshold -float 100
```
