### ISSUE TITLE
10.12升级后有功能失效

### ISSUE THREAD

**Issue by LLinxu** [MacGesture/MacGesture#36]
暂时发现mission control 和显示桌面无论设置任何快捷键，再通过手势，都是无效的。

**Comment by jiegec** [comment]
这看来是和系统的冲突了。但我短时间内不会升级到10.12（也无法，没空间了）。。 @codefalling 有兴趣处理一下？

**Comment by jiegec** [comment]
macOS Sierra看来有不少改动。Karabiner和Seil也挂了。 https://github.com/tekezo/Karabiner/issues/660

**Comment by jiegec** [comment]
有可能需要Access for assistive devices权限。

**Comment by jiegec** [comment]
有用户上报，Sierra上运行没问题。

**Comment by jiegec** [comment]
你好，现在新版本出来了，问题仍然存在吗？

**Comment by LLinxu** [comment]
![2016-11-28 4 13 58](https://cloud.githubusercontent.com/assets/20311436/20660957/1469c31c-b587-11e6-824f-75d9d3c675c1.png)
![2016-11-28 4 14 04](https://cloud.githubusercontent.com/assets/20311436/20660959/146f83ec-b587-11e6-8c62-a9e62dd6f8e2.png)
![2016-11-28 4 15 51](https://cloud.githubusercontent.com/assets/20311436/20660958/146e1566-b587-11e6-8016-dd4c8ca4f5a1.png)
问题依旧

**Comment by LLinxu** [comment]
我设置的control+上／下／左／右。都是失效的。直接用键盘有效，但是鼠标手势无效。

**Comment by jiegec** [comment]
![image](https://cloud.githubusercontent.com/assets/6127678/20670281/37a3e084-b5b3-11e6-8750-9e6a9e215d78.png)
仍然重现不了。嗯。关键是没有Sierra机器无法调试。

**Comment by LLinxu** [comment]
都不更新的吗😂

**Comment by jiegec** [comment]
然而。。机器硬盘没空间了。。而且似乎还有不少软件（比如Karabiner）还没正式支持Sierra呢

**Comment by palxex** [comment]
10.12上虚拟按键似乎有所更改，涉及Fx的都完蛋了（猜测为touchbar相关的修改）。手动在快捷键区改为其他按键，比如我用ctrl+option+cmd+d来作为显示桌面的快捷键即可用macgesture调用。

**Comment by jiegec** [comment]
但这里OP设置的快捷键是C-up,C-down等。。

**Comment by palxex** [comment]
sorry 这个没看到，刚试了下确实如此，估计也是跟Fx一样被系统截胡了？我记得这是多桌面相关的几个默认快捷键。
另外报两个试验结果，sierra上Karabiner-Elements仍然可以发虚拟的Fx按键（ctrl的没试，它现在好像没法发组合键，没细看），不过它的实现底层得多，看起来是直接写了个键盘驱动，然后把特定的物理键盘上所有的事件都hook掉改用那个虚拟键盘发的，它没有用辅助功能。Keyboard Maestro则是用辅助功能实现的，可以做到发Fx和Ctrl+上下左右。路线上看我更看好辅助功能，自己写驱动调试麻烦、对稳定性有威胁、需要跟苹果申请驱动证书、还会导致用户对键盘的设置失效（因为是设置在物理键盘上的）。

**Comment by jiegec** [comment]
嗯，辅助功能应该更好。

**Comment by jiegec** [comment]
我已升级到Sierra，此BUG已确认可以重现。

**Comment by jiegec** [comment]
大概跟踪到问题了：发送的事件是Fn-Control-Up而不是Control-Up

**Comment by jiegec** [comment]
果然。去掉了就成功了。

**Comment by jiegec** [comment]
试试我在https://github.com/MacGesture/MacGesture/issues/60里发的一个版本？

**Comment by jiegec** [comment]
Closed in favor of #60
