### ISSUE TITLE
10.12下全屏后切换时自动弹出偏好面板

### ISSUE THREAD

**Issue by seawink** [MacGesture/MacGesture#37]
程序设置了开机自动启动，没有勾选启动时显示偏好面板。而且没有设置在状态栏显示图标。但是我的程序开启了全屏之后，四指向上切换虚拟桌面的时候，选中全屏化的程序，就会在该程序页面自动弹出偏好面板，切换其他虚拟桌面不会弹出。已经测试过PD，Safari，chrome等程序。PS：手势软件中只设置了3个手势，分别是DR(command+W)，D（command+下），U（command+U）,而且只适用于Safari和Chrome这2个白名单程序。

**Comment by jiegec** [comment]
10.11无法重现。估计是某个事件不应该触发的时候触发了。

**Comment by jiegec** [comment]
然而最大的问题是！我！没！Sierra！机器！

**Comment by jiegec** [comment]
你好，现在新版本出来了，问题仍然存在吗？

**Comment by porsihe** [comment]
同出现这个问题，2.1.2最新版本在10.12依然可以复现

**Comment by gonejack** [comment]
我也常常看到设置面板无故跑出来，不知道什么原因。

**Comment by palxex** [comment]
找到这个事件了：-[AppDelegate applicationDidBecomeActive:]。注掉里面的[self showPreferences]即不会再触发。但不清楚10.12以前这句有没有其他用不敢随便改，请@jiegec看看吧。

**Comment by jiegec** [comment]
嗯，这句的确不需要，是多余的。其它几个部分的事件处理代码已经可以做到singleton。十分感谢 @palxex !

**Comment by jiegec** [comment]
这是修改过的版本，测试（先退出旧的MacGesture再开这个）如果没问题，就可以关闭这个Issue了。
链接: https://pan.baidu.com/s/1qXKdNmk 密码: pquf

**Comment by jiegec** [comment]
有用户反映这个临时版本修复了这个问题。如果还有问题，请re-open.
