### ISSUE TITLE
我的safari鼠标手势不行

### ISSUE THREAD

**Issue by chenbaigunag** [MacGesture/MacGesture#38]
电脑版本： 10.11.6
Safari版本：9.1.6

你好，先真诚感觉这个插件的人性化。
今天下载了最新中文版本的手势，但是开启后，所有配置都是默认的，而且白名单是safari。
但是鼠标手势触发不了，键盘快捷键是可以使用的。
后来，我下载了一个以前的版本：2.0.7 英文版，开启后就能手势了。
所以，中文新版本不知道出问题在哪？

**Comment by jiegec** [comment]
这应该和中文没什么关系吧。。我在我这试试

**Comment by jiegec** [comment]
我这里并没有问题。

**Comment by jiegec** [comment]
请问出现了手势的界面吗？（有箭头和Action名称）

**Comment by chenbaigunag** [comment]
谢谢及时的回复，刚才我又重新下载最新的版本。下载后，打开行了。😂
今天下午的不知道出什么大姨妈了。
感谢。

**Comment by jiegec** [comment]
好的，感谢您对MacGesture的大力支持！
