### ISSUE TITLE
2.1.2 滑鼠左鍵運作異常 

### ISSUE THREAD

**Issue by kuen038** [MacGesture/MacGesture#39]
今天更新後按左键功能有问题， 按按钮会没反应，文字会变成全选整句
感觉跟新增加的鼠标左键手势有冲突
系统是10.12.1 Sierra

现在退回去2.1.1就没问题了。

**Comment by jiegec** [comment]
嗯，知道了，但我这里没有Sierra的机器。我check一下代码

**Comment by jiegec** [comment]
你那边有开发环境吗？

**Comment by kuen038** [comment]
抱歉 没有相关知识 只能使用上遇到问题就来报告一下
这手势软体很好用 太感谢了

**Comment by jiegec** [comment]
嗯，没事。十分感谢您对MacGesture的大力支持！

**Comment by jiegec** [comment]
您能留个邮件吗？我把修改过的App发给您测试？如果不方便，也没事

**Comment by kuen038** [comment]
kuen038@gmail.com
感谢了

**Comment by jiegec** [comment]
测试如何？

**Comment by kuen038** [comment]
还是一样 偶尔左键会没反应 要再按一下 
覆盖回旧版就没事

**Comment by jiegec** [comment]
嗯，知道了，谢谢。

**Comment by jiegec** [comment]
嗯，知道了，谢谢。

**Comment by kuen038** [comment]
好呀 我是直接丢进application 覆盖的 没完整删除 不知道有没有影响

**Comment by jiegec** [comment]
Long time without activity, thus closing.
