### ISSUE TITLE
鼠标滚轮手势存在改进需求

### ISSUE THREAD

**Issue by gonejack** [MacGesture/MacGesture#41]
在Win下使用strokeit这一神器习惯了，养成了很多对鼠标手势的认知。

比如按住右键滚动中键时，设置为了ctrl+tab和ctrl+shift+tab，这样在浏览器上就能通过滚动中键迅速浏览各个标签并且快速切换。

MacGesture做到了滚轮支持非常好，但现在按住右键上下滚动中键时却不能连续触发键盘事件。

我觉得正确的表现应该是像Strokeit一样，按住右键一直滚动时，中键每滚一下都要触发一次按键事件。这样标签就才能连续切换达到浏览效果。

另外，MacGesture不支持对角线画手势吧，对角线手势很适合做窗口缩放，最大最小化当前窗口那样。作者能否考虑添加支持呢

**Comment by jiegec** [comment]
哦，明白你的意思了。就是手势完，可以有三个动作（松开右键，滚轮上，滚轮下），分别触发不同的。对角线手势也可以做，没问题，但改动应该不少。

**Comment by gonejack** [comment]
不不不，我的意思是，按住右键一直往下滚滚轮时，达到的效果应该是ctrl+tab，ctrl+tab，ctrl+tab……滚多少格就触发多少次。现在的情况是，按住右键滚滚轮时，不论滚多少格，都只触发一次。

另外报个bug，我的英文键盘是colemak布局（在输入法设置那里可以调），中文则是qwerty布局的搜狗输入法，我把手势的U设置为了ctrl+command+f，这样来最大化窗口。

现在的bug是，当我把输入法切换为qwerty布局的搜狗输入法（为了打中文）时手势就没法使用。

**Comment by gonejack** [comment]
嗯，在代码上，你的理解没有错。

**Comment by jiegec** [comment]
colemak这个问题在Emacs那边也有，就是按键的时候考虑按键本身对应的字母还是该输入法下字符。如果要切换输入法的话，切换过去又回来体验不是很好，而且输入法切换有个长期未修复的BUG，所以这个方案不好解决（Windows下无论啥输入法都发送原来的keycode）。如果要最小化最前端的窗口，也可以用AppleScript实现。也许也可以Focus一下最面窗口。

**Comment by jiegec** [comment]
我想到这个方案：
1. 规则支持wildcard。可以R*u等。
2. 可以合并连续相同手势
3. 匹配到规则时就应用。

**Comment by gonejack** [comment]
If you want to achieve something like this:
Right click, drag upwards, then every 'u' triggers a 'Next Tab', every 'd' triggers a 'Prev Tab', without releasing right mouse.

right click, without dragging upwards, every u trigger a next tab也是可以的吗？

**Comment by jiegec** [comment]
可以，看你喜好。小心不要冲突就好
