### ISSUE TITLE
跟Synergy在副屏上冲突

### ISSUE THREAD

**Issue by palxex** [MacGesture/MacGesture#42]
环境：
synergy服务端:  macOS 10.12.1, synergy 1.8.4，macgesture 81a8c4e
synergy客户端:  windows 10 1607，synergy 1.8.4
问题：
-1. 若不连接synergy，macgesture在mac上是完全正常的。
0. 若不开启macgesture，连接synergy两边都是正常的。
1. 若先连接synergy再开启macgesture，服务端一切正常，当鼠标移动到客户端上后，按住右键，鼠标光标不再移动，主屏上出现箭头等。
2. 若先开启macgesture再连接synergy，服务端一切正常，当鼠标移动到客户端上后，按住右键开始手势识别，主屏无异常，副屏鼠标滑动距离远超正常范围，看起来是第一段动作的识别结果会叠加到后面的所有部分（比如：若想画DL，在画到L时鼠标会继续按D的方向下滑，即使用户已经停止下滑鼠标。结果就是（鼠标轨迹）一个巨长的D下接一个短短的L）。

期待结果：
鼠标在副屏时macgesture应停止识别，也不对鼠标轨迹施加影响。位置看起来应该是mouseEventCallback这里的if(true)，但怎么改暂时还没想到。估计需要参考[Synergy源代码](https://github.com/symless/synergy)。

**Comment by jiegec** [comment]
我猜Synergy的原理是，在服务端捕捉鼠标事件，如果在客户端区域，就截取之后发送到客户端。但是MacGesture的事件捕捉跑在前面了。

**Comment by jiegec** [comment]
这里的副屏应该是Synergy的概念，而不是多显示器吧。

**Comment by jiegec** [comment]
对了，Debug版会在Console打出右键事件的坐标，看能不能发出来？

**Comment by palxex** [comment]
> 我猜Synergy的原理是，在服务端捕捉鼠标事件，如果在客户端区域，就截取之后发送到客户端。但是MacGesture的事件捕捉跑在前面了。
> 
是的。暂时还没搞清在server端如何判断鼠标在客户端区域，座标并不跟我想的一样会超出屏幕范围而是超出后直接变成(server_screenwidth/2+rnd(-1,1),server_screenheight/2+rnd(-1,1))了。

> 这里的副屏应该是Synergy的概念，而不是多显示器吧。

是的。

**Comment by palxex** [comment]
> 对了，Debug版会在Console打出右键事件的坐标，看能不能发出来？
> 

wow，我刚才在win7里又测了一下（这个client是1.8.6的），情况跟上面win10+1.8.4的不同。场景1不变还是那个问题，但场景2的鼠标不正常滑动消失了，也就是现在只要保证服务端synergy在macgesture之后启动就完全没问题！之后回到win10确认了下，场景2的问题应该是synergy老版本的问题，现在问题减少了一半:) 又及：这种情况下，副屏的右键点击压根没有log。
关于情况1的数据，为免自己观测失误我下面给一下。下面5组数据分别是在win客户端差不多左上角、右上角、正中、左下角、右下角右键单击的。另win本（1366，768），mac显示器（1600，800）。
2016-12-14 22:57:23.432708 MacGesture[70539:2064018] frame:{{0, 0}, {1600, 900}}, window:{{0, 0}, {1600, 900}}, screen:{{0, 0}, {1600, 900}}
2016-12-14 22:57:23.432777 MacGesture[70539:2064018] {800, 450.24609375}
2016-12-14 22:57:27.683820 MacGesture[70539:2064018] frame:{{0, 0}, {1600, 900}}, window:{{0, 0}, {1600, 900}}, screen:{{0, 0}, {1600, 900}}
2016-12-14 22:57:27.683898 MacGesture[70539:2064018] {800.7265625, 450}
2016-12-14 22:57:29.850907 MacGesture[70539:2064018] frame:{{0, 0}, {1600, 900}}, window:{{0, 0}, {1600, 900}}, screen:{{0, 0}, {1600, 900}}
2016-12-14 22:57:29.850968 MacGesture[70539:2064018] {800, 449.7578125}
2016-12-14 22:57:32.538723 MacGesture[70539:2064018] frame:{{0, 0}, {1600, 900}}, window:{{0, 0}, {1600, 900}}, screen:{{0, 0}, {1600, 900}}
2016-12-14 22:57:32.538792 MacGesture[70539:2064018] {798.76953125, 449.38671875}
2016-12-14 22:57:36.274248 MacGesture[70539:2064018] frame:{{0, 0}, {1600, 900}}, window:{{0, 0}, {1600, 900}}, screen:{{0, 0}, {1600, 900}}
2016-12-14 22:57:36.274299 MacGesture[70539:2064018] {800.2421875, 449.515625}

**Comment by jiegec** [comment]
我看看周末有没有时间在我的Windows机器上联调吧。。

**Comment by jiegec** [comment]
我这也试出来了：先Synergy后MG，手势的时候正常，也出不去server的屏幕。反过来就有问题。

**Comment by jiegec** [comment]
到了副屏后自动回到了中间。

**Comment by jiegec** [comment]
可以做到检测并且取消手势了。
```
// Hack when Synergy is started after MacGesture
                // -- when dragging to a client, the mouse point resets to (server_screenwidth/2+rnd(-1,1),server_screenheight/2+rnd(-1,1))
                if (mouseDraggedEvent) {
                    NSPoint lastPoint = CGEventGetLocation(mouseDraggedEvent);
                    NSPoint currentPoint = [mouseEvent locationInWindow];
                    NSRect screen = [[NSScreen mainScreen] frame];
                    float d1 = fabs(lastPoint.x - screen.origin.x), d2 = fabs(lastPoint.x - screen.origin.x - screen.size.width);
                    float d3 = fabs(lastPoint.y - screen.origin.y), d4 = fabs(lastPoint.y - screen.origin.y - screen.size.height);
                    
                    float d5 = fabs(currentPoint.x - screen.origin.x - screen.size.width/2), d6 = fabs(currentPoint.y - screen.origin.y - screen.size.height/2);
                    
                    const float threshold = 30.0;
                    if ((d1 < threshold || d2 < threshold || d3 < threshold || d4 < threshold) &&
                        d5 < threshold && d6 < threshold) {
                        CFRelease(mouseDraggedEvent);
                        CFRelease(mouseDownEvent);
                        mouseDownEvent = mouseDraggedEvent = NULL;
                        shouldShow = NO;
                        [windowController reinitWindow];
                        resetDirection();
                        break;
                    }
                    
                }
```

**Comment by palxex** [comment]
呃……请给下修改的上下文，我没搞清放在哪有用……

**Comment by jiegec** [comment]
这里的意思就是判断如果上一个鼠标的位置在屏幕边缘，这次突然到了中间，就取消。

**Comment by palxex** [comment]
嗯好的，代码的意思看懂了，就是昨天没搞清是加在那里的。刚从master上拉了最新的代码，这下不用猜啦。
第一次测试印象中相当完美，问题解决的感觉。但再启动一次却又出问题了，而且后面每次都出，出的问题跟之前一样。验证了下我这只要有(d1 < threshold || d2 < threshold || d3 < threshold || d4 < threshold)这个判断条件，在副屏进行鼠标右键拖拽，鼠标指针就会钉在主屏上，副屏压根不动。但如果简单去掉，问题就成了副屏上右键拖拉直接变成了hover。另外加不加这个判断，副屏上直接右击都会触发主屏上的中心右击事件。
个人的需求是副屏上鼠标手势交给其本地的鼠标手势app（比如wgesture）判断，有可能的话，感觉macgesture最好在判断出事件的起始发生位置发生不在mac屏幕上后就直接将事件转发给macOS。

**Comment by jiegec** [comment]
问题就是，MacGesture事件处理在Synergy前（因为后启动），所以Synergy做的事情都要下一次Loop才知道。也无法判断是否在副屏，除非和Synergy高度集成

**Comment by jiegec** [comment]
问题就是，MacGesture事件处理在Synergy前（因为后启动），所以Synergy做的事情都要下一次Loop才知道。也无法判断是否在副屏，除非和Synergy高度集成

**Comment by palxex** [comment]
确实暂时想不到什么好辙来实现。要不就先作为known issue记录吧，反正也能靠规定启动顺序解决。说到集成，synergy有个plugin机制，它的ssl加密就是用那个做的，但我不太确定（至少接口）是否开源了。抱歉占用了你一个周末做这种corner case哈。

**Comment by jiegec** [comment]
对了，有兴趣帮手MacGesture开发吗？有好几个客户反应Sierra上出现一些BUG，我这El Capitan都不能重现。。。也没有硬盘空间给我升级Sierra。

**Comment by palxex** [comment]
呃，我是挺想说没问题……但说实话我是折腾cocoa touch的，涉及cocoa跟系统结合的问题未必能搞定，另外时间上不好保证。要不这样，我什么时候有空就看看，能解决的就发PR——要直接改我还怕在10.12下改出问题——不能解决或者找到问题但不知道你之前怎么考虑的就先把此类问题在sierra上我能重现的情况和自己的分析发到对应issue去。刚发了issue 36/37的（我看open的似乎也就这俩跟sierra相关），有其他需要的直接@我吧。

**Comment by jiegec** [comment]
嗯，十分感谢您的支持！还有一些比较零散的反馈在QQ群上，有一个涉及到滚轮事件比较严重。

**Comment by palxex** [comment]
不在群里，建议也单开一个issue吧:)
