### ISSUE TITLE
一些开发IDE中会有问题，如果设置了手势，右键菜单就出不来了

### ISSUE THREAD

**Issue by shuifengYu** [MacGesture/MacGesture#44]
我现在发现的有Android Studio 和WebStorm两个IDE，因为这两个IDE右键菜单是在右键down的事件中触发的，现在被你这个事件被拦截了，导致在IDE中出不来菜单，估计无解吧这个问题，在开发的时候只能不使用手势了

**Comment by shuifengYu** [comment]
应该说所有在down事件触发菜单的app都会有这个问题吧

**Comment by jiegec** [comment]
不会呀，代码写的是，如果触发不了，就把右键MouseDown发回去。另外就是这些IDE用的是Java，所以没有bundle id。。所以过滤就坑了

**Comment by jiegec** [comment]
我这里测试是，单击右键松开，就会把mousedown和mouseup发送。否则就没有。

**Comment by gonejack** [comment]
我也碰到了，WebStorm无法打开右键菜单。

**Comment by Pinphoo** [comment]
开启手势后WebStorm右键菜单弹不出来了，现在只能排除掉WebStorm，除了这点遗憾，其它还是挺完美的。

**Comment by jiegec** [comment]
嗯，这个是个长期问题，目前没找到办法修复

**Comment by Pinphoo** [comment]
找到一个方法：在WebStorm的[Preferences]-[KeyMap]中设置”Show Context Menu“的快捷键为"Button3 Click"可解决该问题。虽然偶尔还是会弹不出菜单，但已接近完美。

**Comment by jiegec** [comment]
十分感谢！@gonejack @shuifengYu 你们试试？如果可以，我就放到README里说明一下

**Comment by jiegec** [comment]
PING?

**Comment by dss886** [comment]
奇了怪了，设KeyMap的办法在我家里电脑上可行，很完美，但是到公司电脑上就死活不行……Android Studio 2.3.1

**Comment by MarnoDev** [comment]
我试了，可以解决

**Comment by jiegec** [comment]
最新版本2.2.3应该已经修复.如果还有问题,请reopen.

**Comment by UnleashHell** [comment]
@Pinphoo 我在keymap里无法直接设置为Button3 Click，点击右键会设置为command Button3 Click，你没有这个问题吗？
http://owicp4z3x.bkt.clouddn.com/20180507003517_OCIRy2_Screenshot.jpeg

**Comment by dss886** [comment]
@UnleashHell 试一下先关了MacGesture再设置keymap，设置完再开MacGesture
