### ISSUE TITLE
用户反映MacGesture占用内存过大。一定是内存泄漏问题。

### ISSUE THREAD

**Issue by jiegec** [MacGesture/MacGesture#46]
看截图基本都在1G左右。估计是在Sierra上。谁能帮忙Instruments一下看看内存泄漏吗？

**Comment by CodeFalling** [comment]
![image](https://cloud.githubusercontent.com/assets/5436704/21465390/a6e558e6-c9dc-11e6-940f-90fd7f9e6677.png)

macOS 10.12.1，没有出现类似问题，需要更多步骤复现？

**Comment by fengcen** [comment]
![image](https://cloud.githubusercontent.com/assets/6973379/25309294/080b0878-27fc-11e7-8bb7-84ecf17db612.png)
我的也是，长时间运行后发现的。

**Comment by jiegec** [comment]
开了多久？可以看看MacGesture的cputime吗

**Comment by fengcen** [comment]
@jiegec 不记得了，mac 大概有两天没重启了，刚看了下，占用了 2.5 GB，刚看了你的回复，再去看一眼，结果减少到了 40 MB，可能会不定时 GC？
<img width="668" alt="2017-04-25_22-45-39" src="https://cloud.githubusercontent.com/assets/6973379/25391506/f971130c-2a08-11e7-906f-fb27bf97c7f9.png">

**Comment by jiegec** [comment]
还是很奇怪。。。我这就是没有这个问题。。。

**Comment by fengcen** [comment]
据我这几天的观察，内存占用几分钟到几小时之内会慢慢上升，到了几百 MB 或者 1~2GB 之后，内存占用可能会在某个时间降下来，然后又重复这个过程。

可能是资源没释放，如果语言支持 GC 的话就是引用没解除咯。

现在能降下来，找不到原因也暂时没有多大影响。

**Comment by jiegec** [comment]
试试这个fix：链接: https://pan.baidu.com/s/1o8bPX4Q 密码: cetz

**Comment by fengcen** [comment]
还是和之前一样，我的系统是 10.11.6

**Comment by jiegec** [comment]
看来还有别的泄漏。。我这把Instruments检测出来的泄漏修复了。

**Comment by jiegec** [comment]
Long time without activity, thus closing.
