### ISSUE TITLE
希望有规则导出和导入功能！

### ISSUE THREAD

**Issue by varjay** [MacGesture/MacGesture#47]
希望有规则导出和导入功能！

每次重装系统还要重新设置太麻烦了，求加入！

**Comment by jiegec** [comment]
嗯，其实这个功能用一些备份软件也可以完成（其实文件就在哪里，cocoa程序员都知道。。）。。写一个按钮出来也可以。我想想怎么做比较好。

**Comment by jiegec** [comment]
用命令行的方法就是，运行
```
defaults export com.codefalling.MacGesture backup.plist
```

然后要恢复的时候，把backup.plist拷过来，然后
```
defaults import com.codefalling.MacGesture backup.list

**Comment by varjay** [comment]
太好了，加入了导入导出功能。接下来可以再优化一下，比如规则的过滤名称那里，要是能直接显示应用名称或应用图标，那就太棒了！

**Comment by jiegec** [comment]
“从运行中的App中选取”
