### ISSUE TITLE
装有MacGesture 2.2 与Parallels Desktop 的rMBP上的奇怪现象

### ISSUE THREAD

**Issue by hadesshen** [MacGesture/MacGesture#48]
我的MacBook装有MacGesture 2.2 与Parallels Desktop 12。
PD12上装的Win7虚拟机，全屏的状态。
在我每次在用Mission Control切换桌面到Win7虚拟机的时候，MacGesture 2.2窗口就会自动弹出来，
这让我很是困惑呀～

**Comment by jiegec** [comment]
2.2版本？写错了吧？估计还是那个BUG，我马上把一个临时修复版（下一个版本就有这个修复）连接发一下。

**Comment by hadesshen** [comment]
嗯，试了一下，没有问题了，非常感谢！！

**Comment by jiegec** [comment]
有用户反映这个临时版本修复了这个问题。如果还有问题，请re-open.
