### ISSUE TITLE
Mouse buttons combinations

### ISSUE THREAD

**Issue by ww7** [MacGesture/MacGesture#49]
xGestures have gestures named 
Rock Left — chord fromRight Button to Left Button 
Rock Right — chord from Left Button to Right Button   
additionally would be cool extend with Middle Button and Scroll Up/Down

**Comment by jiegec** [comment]
Scroll Up/Down are already implemented. From Right Button to Left Button too.

**Comment by ww7** [comment]
Z not work with Trigger like u, d and others.

**Comment by jiegec** [comment]
I don't understand "Z not work with Trigger like u, d and others.".

**Comment by ww7** [comment]
Mouse L (Z) not work with Trigger. 

Example: I wish to create Rule for cmd+w with U*Z+Trigger. 
And I expect it's works like U*u +Trigger, gesture Up and every click Mouse L is send cmd+w.

If Trigger is "on", Rule just not working.

**Comment by jiegec** [comment]
I think it has been fixed in master.
