### ISSUE TITLE
Filter wildcard for "not"

### ISSUE THREAD

**Issue by ww7** [MacGesture/MacGesture#50]
So hard to set all app's where MacGesture will send action
If set "*" than need wildcard for exclude

**Comment by jiegec** [comment]
It is reported that '!' is supported to exclude.

**Comment by ww7** [comment]
What correct syntax for exclude?
*|!chrome — not work

**Comment by jiegec** [comment]
I don't know how too. Here is the original message.
```
小石星人 13:04:43
!com.sublimetext.3|
```

**Comment by ww7** [comment]
Report !com.google.Chrome|* — not work

**Comment by jiegec** [comment]
It does not work. I may implement it sometime.

**Comment by jiegec** [comment]
Implemented in commit b9f6fc4
