### ISSUE TITLE
Symbol * in gesture (not in filter)

### ISSUE THREAD

**Issue by ww7** [MacGesture/MacGesture#51]
Only for gestures with Scroll Up/Down ?

**Comment by jiegec** [comment]
Mouse left click can be supported as well. Just not implemented yet.

**Comment by ww7** [comment]
What mean * in gesture? 

example: UL works, U*L works too

**Comment by jiegec** [comment]
Yes, but UL only matches UL, while U*L can match UuL, UuuL, UZuldrL etc

**Comment by ww7** [comment]
Thank You
