### ISSUE TITLE
可以支持手势录制吗？

### ISSUE THREAD

**Issue by fengcen** [MacGesture/MacGesture#53]
StrokeIt 支持手势录制，如果这个功能比较复杂，可不可以考虑支持向四个角的斜线一样的手势，比如 向右上角，向左下角，向左上角，向右下角 这四个手势？

**Comment by jiegec** [comment]
手势录制可以考虑。斜线手势不想加，因为会影响到上下左右四个方向的自由度。

**Comment by fengcen** [comment]
我用 StrokeIt 的时候好像没觉得有影响到自由度，也没有误触发，我用了四个方向的手势，也用了垂直角的手势

**Comment by jiegec** [comment]
因为我拖上下左右的时候比较“随性“。。。

**Comment by fengcen** [comment]
好吧。如果加这个难度比较小的话可以考虑加一下然后给用户选择要不要用这个手势，如果加了有其他影响的话那就不加了，现在用起来还是很好的。
