### ISSUE TITLE
可以支持自动激活窗口并应用该手势在最上层的应用吗？

### ISSUE THREAD

**Issue by fengcen** [MacGesture/MacGesture#54]
StrokeIt 的手势是应用在最上层的窗口，不管该窗口是否处于激活状态，但是 MacGesture 必须先点击该窗口激活之后，才能应用手势。能否改成像 StrokeIt 一样的行为？技术难度大吗？谢谢你的开发，这个应用基本满足我的需求。

**Comment by jiegec** [comment]
你指的是鼠标指向的窗口吧。现在是focus的窗口，和系统行为一致。

**Comment by jiegec** [comment]
曾经也有用户提过这个问题。我觉得各有优劣吧，看需求

**Comment by fengcen** [comment]
会有什么劣势吗，比如鼠标的起点不准确就触发了错误的窗口？这个我用 StrokeIt 的时候也没有感觉到，不知道其他人的情况

**Comment by jiegec** [comment]
嗯，是的，而且判断的依据可能不止一个：初始位置、结束位置、如果在划手势期间窗口变了咋办

**Comment by fengcen** [comment]
StrokeIt 的触发是根据起点的。根据起点应该没问题。

> 如果在划手势期间窗口变了咋办

会有这种情况吗？我没遇到过。
