### ISSUE TITLE
MacGesture disables Right-Click in Intellij IDEA (Java-based applications?)

### ISSUE THREAD

**Issue by kstenschke** [MacGesture/MacGesture#57]
When MacGesture is running, right clicking does not work inside Intellij IDEA (https://www.jetbrains.com/idea/download/) anymore.
To be checked: maybe this concerns all java-based apps?
Guess: it seems like propagation of the click-event is  stopped / the event is being unset overall.

**Comment by jiegec** [comment]
Yes this is a long-standing bug. See #44 and #20.

An imperfect solution from issue #44 is here:
```
找到一个方法：在WebStorm的[Preferences]-[KeyMap]中设置”Show Context Menu“的快捷键为"Button3 Click"可解决该问题。虽然偶尔还是会弹不出菜单，但已接近完美。
```
I can provide English translation when needed.

**Comment by kstenschke** [comment]
Thank you for the hint. It is a bit quirky (context menu position doesn't relate to the mouse position) but works somehow 👍

**Comment by jiegec** [comment]
So this should be mentioned in known issues. Done. Thanks.
