### ISSUE TITLE
不能录制Mac全局快捷键的问题

### ISSUE THREAD

**Issue by imyzf** [MacGesture/MacGesture#58]
首先非常感谢作者，这个软件很好用，找了好久了。

但是我想录制切换workspace的`ctrl` `→`这种快捷键的时候，就无法记录，直接生效了。之前用better control tool是可以记录的。现在我只能用apple script解决，比较麻烦。

```
tell application "System Events"
    key code 123 using {control down}
end
```

系统：Mac OSX 10.11.6

**Comment by jiegec** [comment]
嗯，这个是已知问题，系统捕捉ctrl+right先于MacGesture，所以有这个问题。解决方法是先取消系统绑定，在MacGesture修改后再回复。

**Comment by jiegec** [comment]
Closed in favor of issue #60
