### ISSUE TITLE
无法开启偏好设置面板

### ISSUE THREAD

**Issue by javenfeng** [MacGesture/MacGesture#61]
我设置了启用后不开启面板，然后取消了菜单栏的图标，同时开机自启。
如此，我双击打开应用程序，却再也看不到设置面板了。
请问如何解决？

**Comment by jiegec** [comment]
已确认。

**Comment by jiegec** [comment]
和 #37 的FIX有关。现在macOS似乎把切换desktop时触发那个事件取消了。

**Comment by javenfeng** [comment]
沒有看太明白，我還是無法呼出面板。請問意思是當前無法解決嗎？

**Comment by jiegec** [comment]
是这样的：以前实现这个功能的代码在一些macOS版本下会在切换Desktop时被调用，于是被删掉了。建议用AppleScript+手势唤出面板，这个方法不受影响。

**Comment by jiegec** [comment]
Fixed in favor of commit 8239c13. Will be incorporated in next release.
