### ISSUE TITLE
稳定性不足，经常崩溃

### ISSUE THREAD

**Issue by dss886** [MacGesture/MacGesture#62]
经常用一段时间程序就自己没了…也没有日志也没有错误提醒

今天遇到了另外一个问题，如下图，重启电脑才好

![2017-06-30 5 36 14](https://user-images.githubusercontent.com/5170950/27730341-6f7510c2-5dbb-11e7-9cb3-8582db9a5e4f.png)

**Comment by jiegec** [comment]
试试从命令行运行MacGesture。看看错误信息是什么。至于AppleScript的错误，则是AppleScript本身抛出的异常被显示出来而已，得看AppleScript写得是否正确。

**Comment by bytemain** [comment]
Can't repro, close it.
