### ISSUE TITLE
通过applescript调用Chrome，但是没有安装chrome，会死机。

### ISSUE THREAD

**Issue by daodao6283** [MacGesture/MacGesture#63]
通过applescript调用Chrome，但是没有安装chrome，系统会弹出一个窗口询问chrome被安装在哪里，这个窗口无法关闭，而且永远前置。只能通过重启或者强制注销来解决。

**Comment by jiegec** [comment]
能在这写一下你的AppleScript吗？

**Comment by bytemain** [comment]
目前无法复现，先关了，有问题可以再打开。
