### ISSUE TITLE
Feature request: Add this to homebrew cask

### ISSUE THREAD

**Issue by rhacker** [MacGesture/MacGesture#65]
I think we should add this to homebrew cask.

**Comment by jiegec** [comment]
Thanks for your advice. But I have no idea on how to add this to homebrew-cask.

**Comment by seagle0128** [comment]
@jiegec Please refer to these wikis.
https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md
https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md

**Comment by jiegec** [comment]
MacGesture is not stable enough. We should fix those tough BUGS before adding to homebrew-cask.

**Comment by seagle0128** [comment]
Agree. I just provide some references. Thanks!

**Comment by jiegec** [comment]
Done.
