### ISSUE TITLE
怎么好久没更新了?

### ISSUE THREAD

**Issue by ds462716** [MacGesture/MacGesture#67]
java软件右键失灵的问题能解决不?  有方案没?有的话我可以实现下

**Comment by jiegec** [comment]
有一个不完美的解决方案在readme里面有，具体原因未知。一段时间没有更新是因为不知道更新啥并且我开学了。。。

**Comment by jiegec** [comment]
应该已经在最新版本2.2.3解决.如果还有问题请reopen.另外我已经死于数学的海洋中hh
