### ISSUE TITLE
java 程序右键不能用的问题解决了吗?

### ISSUE THREAD

**Issue by ds462716** [MacGesture/MacGesture#70]
java 程序右键不能用的问题解决了吗?  BetterAndBetter 这个软件已经解决了  可以借鉴下

**Comment by jiegec** [comment]
然额那个软件不开源吧。。。我也不知道怎么借鉴啊

**Comment by ds462716** [comment]
不是在一个群里吗?  问问不就得了

**Comment by ds462716** [comment]
你这个软件确实比他那个好用  希望解决这个就完美了

**Comment by ds462716** [comment]
![image](https://user-images.githubusercontent.com/8003152/31443911-4b205b82-ae60-11e7-9d05-a5d462997fb3.png)

**Comment by ds462716** [comment]
Alex  12:37:51
第一个问题，我发现只要if (!mouseDraggedEvent) {
                    CGEventPost(kCGSessionEventTap, mouseDownEvent);
  
                    usleep(1000);
             
                    CGEventPost(kCGSessionEventTap, event);
                    
                }
Alex  12:38:16
在中间加个usleep就好了
Alex  12:39:23
触发系统快捷键，我是在输入时临时禁止了快捷键触发，输入后再恢复
Alex  12:40:22
第三个其实就是用你的办法，无法是在app里面判断是否要抵消 Fn 键的作用
