### ISSUE TITLE
Use without filter

### ISSUE THREAD

**Issue by Req** [MacGesture/MacGesture#72]
How can I configure a gesture to work globally? I want a gesture to not be only in certain programs but in all current and future programs and also the desktop (Global applescript things like "go to sleep", "play/pause spotify", "turn on VPN" and such)

I can't seem to find like a filter "*" or just leave it empty. Thanks!

**Comment by jiegec** [comment]
The filter "*" does want you want.

**Comment by Req** [comment]
Great that it's possible - but how? When I click a rule and then click "choose running app" I don't see that filter. If I uncheck everything the filter column is just empty. @jiegec

**Comment by jiegec** [comment]
You can edit that filter directly -- by clicking on it. Due to macOS's bad handling of double-click detection, the experience is not well thoug.
