### ISSUE TITLE
Bug: Desktop tearing and `WindowServer` CPU load after some time

### ISSUE THREAD

**Issue by michalzelinka** [MacGesture/MacGesture#73]
On my configuration (Mac mini, 2×1980×1200px screens) the MacGesture causes the window server to start tearing during animations (swiping between Desktops, scrolling in various windows, mainly browsers with complex content displayed) and consume more CPU over some time.

I've done some experiments and I've probably found the cause.

`CanvasWindowController` tends to re-initialize its window pretty often – seems like after every gesture + some extra events I guess? The bad thing is the old window isn't released correctly and stays allocated in the memory (found via Memory Graph) and most probably in the view hierarchy as well, causing the window server to handle events on multiple instances of `CanvasWindow`/`CanvasView`.

I've tried to disable this re-initialization by quitting `-reinitWindow` immediately when there's already some active window available (`self.window != null`). By doing this, all the symptoms listed above have passed. That's probably not the correct way of fixing this ('cause I don't know about all the specific reasons to re-initialize the window – although it worked with only single init for a couple of hours) but there's definitely something buggy (retaining when not wanted) and inefficient about this recycling.

I suspect this may address some MacGesture memory issues as well.

**Comment by jiegec** [comment]
Thanks very much!!!!
Busy investigating...

**Comment by jiegec** [comment]
Could you please try this version?
[MacGesture.app.zip](https://github.com/MacGesture/MacGesture/files/1432761/MacGesture.app.zip)

Currently I just change that code to:
```
    if (self.window != NULL) {
        [self.window close];
    }
```
Because it seems that the code below can be used to support multiple screens.

**Comment by michalzelinka** [comment]
I've performed a following patch:
```diff
 - (void)reinitWindow {
+
+    if (self.window != NULL) {
+        [self.window close];
+    }
+
     NSRect frame = NSScreen.mainScreen.frame;
```

and it seems it addresses the issues mentioned. 👍

**Comment by michalzelinka** [comment]
BTW I think the screens/display area changes are delivered another way using notifications with a re-init call in that place. I don't think there's a need to re-init the window after each gesture explicitly.
