### ISSUE TITLE
与Snagit 2018 冲突

### ISSUE THREAD

**Issue by kbrx93** [MacGesture/MacGesture#75]
开启MacGesture后，用snagit截图的话不能智能识别窗口，只能全屏或手动选取。
虽然可以通过暂时关闭MacGesture来解决，但总是多点麻烦。
环境： Mac 10.12
            snagit 2018(90407)
            MacGesture(2.2.3)

**Comment by kbrx93** [comment]
如果目前并无计划更改此冲突的话，请通知我关闭问题，谢谢。

**Comment by kbrx93** [comment]
如果目前无计划更改或修复此种突的话，请通知我关闭问题。

**Comment by jiegec** [comment]
。。。这玩意儿要钱。。突然发现是techsmith出品的，以前用过它的camtasia...

**Comment by jiegec** [comment]
大概是因为MacGesture创建了一个全屏的透明窗口。。。？

**Comment by jiegec** [comment]
但是系统自带的截图的识别窗口是不受这个影响的

**Comment by kbrx93** [comment]
应该是，MacGesture目前是通过在这个全屏的透明窗口上工作所以无法取消吗？

**Comment by bytemain** [comment]
目前无法复现，先关了，有问题可以再打开。
