### ISSUE TITLE
升级系统后卡死整台电脑

### ISSUE THREAD

**Issue by calabashdad** [MacGesture/MacGesture#81]
每次系统更新我都更新了，系统升级之前用的一直很流畅，但是最近一段时间，只要打开浏览器用一段时间(大约是频繁操作十几分钟，不是很频繁时间长点大约三四十分钟)就必然导致整个卡死，只有强制关机才行

找到规律后我赶在卡死之前看了下系统资源，发现macgesture的内存已经到了1g，就临时卸载，后来再没出现过卡死的现象了

希望提供了点有用信息以帮助更好的提高

**Comment by calabashdad** [comment]
补充下，和浏览器没关系，我试了Safari和chrome，都是一样

**Comment by jiegec** [comment]
Duplicate of https://github.com/MacGesture/MacGesture/issues/69 . Unable to fix
