### ISSUE TITLE
macGesture导致High Sierra全局图形化界面拖慢

### ISSUE THREAD

**Issue by YoshiyukiSakura** [MacGesture/MacGesture#82]
在开机并使用macGesture一段时间以后，会明显感觉到手势轨迹的描绘要晚于真实鼠标移动，并且其他系统动画也存在掉帧现象。
该问题在退出MacGesture以后会复原，再次允许macGesture一段时间后能够大概率复现。
系统版本10.13.3软件版本2.2.3

**Comment by AmazingIri** [comment]
Please reference to #69 . Current solution is to rollback to 2.2.1.

**Comment by ds462716** [comment]
作者  这个问题还没解决吗?

**Comment by shensmart** [comment]
用iStatmenu监控，看到应该是显存那边溢出了，用一会显存就满了，现在用回2.2.1，暂时没事了
