### ISSUE TITLE
MacGesture对safari支持不错，但chrome支持有问题

### ISSUE THREAD

**Issue by hcpub** [MacGesture/MacGesture#83]
就是按住鼠标右键划手势时，总是会弹出右键菜单，只有通过插件让chrome变成双击右键弹出菜单才行，但这样设置的话，在触控板情况下，就根本无法弹出右键菜单。
另一款别人开发的小工具BetterAndBetter的鼠标手势可以完美支持chrome，不会出现鼠标手势时弹出右键菜单的情况，希望可以对chrome做下优化

**Comment by jiegec** [comment]
项目开发已经停滞，如果有兴趣的话，可以提交pull request进行改进。

**Comment by bytemain** [comment]
目前无法复现，先关了，有问题可以再打开。
