### ISSUE TITLE
bug: 无法在 Mojave 系统下使用

### ISSUE THREAD

**Issue by membphis** [MacGesture/MacGesture#86]
无法启动

**Comment by CodeFalling** [comment]
是因为 Mojave 的隐私权限策略又改了，已经在 https://github.com/MacGesture/MacGesture/releases/tag/fix-crash-on-mojave 版本中修复，可以下载试用，记得在隐私设置中打开；如果已经打开但是仍然不工作，先移除设置再重新信任。

![image](https://user-images.githubusercontent.com/5436704/47252957-71347b00-d47f-11e8-943f-8a82ea4fe47c.png)

**Comment by membphis** [comment]
重新移除加入后，确实好使
