### ISSUE TITLE
外接显示器手势路径错位，屏幕右侧区域窗口元素无法点击

### ISSUE THREAD

**Issue by lyericwang** [MacGesture/MacGesture#90]
系统 10.14.2
MacGesture版本  2.2.4 fix crash on macOS Mojave
外接一个显示器，在外接显示器上，右键画出手势不会在绘画的地方显示手势路径，而是在屏幕最右侧显示路径，而且最右侧部分此时鼠标左键点击会自动绘制一条直线路径，在这个区域中的所有窗口元素都无法点击。
![image](https://user-images.githubusercontent.com/34962589/50578694-1accbb00-0e78-11e9-870e-20225faf11ad.png)
上传了一个视频，应该更直观一些。
链接:https://pan.baidu.com/s/11Zmu5D1aehbpWgimUcowgA  密码:lofo

退出软件重新打开问题消失，十几二十分钟后又出现了，有时候自己会消失，过一会又出现。

**Comment by jiegec** [comment]
有改变过显示之间的相对位置吗？

**Comment by lyericwang** [comment]
> 有改变过显示之间的相对位置吗？

多谢回复。这个时间太长有点忘记了，默认的好像外接是在左侧的，自己调成外接在右侧了，其他设置没动过。跟这个有关吗？
<img width="666" alt="2019-01-02 10 48 21" src="https://user-images.githubusercontent.com/34962589/50579005-fe328200-0e7b-11e9-93ed-9d862e40072a.png">
<img width="670" alt="2019-01-02 10 47 50" src="https://user-images.githubusercontent.com/34962589/50579006-fe328200-0e7b-11e9-92b0-02a298562ba9.png">

**Comment by jiegec** [comment]
有关。现在只在刚开启程序的时候获取显示排布，之后默认没有变。

**Comment by orchidflower** [comment]
这个问题我也碰到过，应该是bug引起的，我已经修复过了。刚刚创建了PR， 自己测试过很长时间了，表现正常。 #91

**Comment by wbright** [comment]
2.25内存泄露的问题解决了吗

**Comment by jiegec** [comment]
您好，这边还是不能重现内存泄露的问题。
