### ISSUE TITLE
mojave 下执行手势操作时出现一小段鼠标轨迹，然后卡死

### ISSUE THREAD

**Issue by gneheix** [MacGesture/MacGesture#94]
chrome/safari下结果类似，截图效果：
![image](https://user-images.githubusercontent.com/31443271/51510437-01e07580-1e38-11e9-8b23-baa68fda16a1.png)

![image](https://user-images.githubusercontent.com/31443271/51510501-466c1100-1e38-11e9-9a67-08f51e7709bb.png)

之后无法打开偏好设置，调度窗口显示空白面板：
![image](https://user-images.githubusercontent.com/31443271/51510593-a95da800-1e38-11e9-8a1e-4107858342e7.png)

无法使用，只能退出app。

**Comment by todebug** [comment]
跟楼主一个问题.应该是通病,望作者大大能够解决.谢谢.

**Comment by JJ7539** [comment]
进入“偏好设置>常规>手势”，取消勾选“显示手势说明”，即可解决。
我的macOS Mojave版本：10.14.5 (18F132)

**Comment by todebug** [comment]
已经解决了，不过仍然感谢

**Comment by bytemain** [comment]
目前无法复现，先关了，有问题可以再打开。
