### ISSUE TITLE
鼠标是否考虑支持斜手势？

### ISSUE THREAD

**Issue by lins1** [MacGesture/MacGesture#97]
类似于windows下的wgestures，加入右上、左上、左下、右下四个一笔直接画的斜手势？

**Comment by jiegec** [comment]
曾经实现过，但是发现效果不好，识别的时候会出现左上和左边不好区分的情况，于是没有继续做。

**Comment by jiegec** [comment]
如果有更好的识别算法（而不是目前的按照角度+阈值），也欢迎提出。

**Comment by mtjo** [comment]
> 类似于windows下的wgestures，加入右上、左上、左下、右下四个一笔直接画的斜手势？

MacStroke 实现完全自定义手势 基于这软件做的 https://github.com/mtjo/MacStroke/releases
